services:
  jenkins_assign4:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080" 
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always


volumes:
  jenkins_home: